version: 2
jobs:
  build:
    docker:
      - image: abcum/circle-golang:latest
    working_directory: /go/src/github.com/abcum/rixxdb
    steps:
      - checkout
      - run:
          name: Clean
          command: make clean
      - run:
          name: Glide
          command: make glide
      - run:
          name: Tests
          command: make tests
      - run:
          name: Cover
          command: make cover
